### ISSUE TITLE
Does Bootloader_LDROM.bin support NuMicro ISP Programming Tool?

### ISSUE THREAD

**Issue by wally0258** [OpenNuvoton/NuMaker-mbed-AWS-IoT-CSDK-OTA-example#1]
Hello,

Can I use [NuMicro ISP Programming Tool](https://www.nuvoton.com/resource-download.jsp?tp_GUID=SW0320101221101703) to locally upgrade software via CANbus through "Bootloader_LDROM.bin" provided by this example?.

**Comment by ccli8** [comment]
No. The attached `Bootloader_LDROM.bin` doesn't support NuMicro ISP Programming Tool. Instead, it reads update firmware image from SPI flash and re-programs APROM.
